Repository hashicorp-forge/hermes, pull requests merged in 2023-07, with the labels that each got.

#259 Improve resource highlighting
  web/app/components/document/sidebar/related-resources.ts
Labels: bugfix

#256 Add tooltip animation props
  web/app/modifiers/tooltip.ts
  web/app/styles/components/tooltip.scss
Labels: enhancement

#260 Add spinner to Related Resources search
  web/app/components/document/sidebar/related-resources.hbs
  web/app/components/document/sidebar/related-resources.ts
  web/app/components/document/sidebar/related-resources/add.hbs
  web/app/components/document/sidebar/related-resources/add.ts
  web/tests/integration/components/document/sidebar/related-resources/add-test.ts
Labels: enhancement

#261 Add API for shareable drafts
  configs/config.hcl
  internal/api/documents.go
  internal/api/documents_test.go
  internal/api/drafts.go
  internal/api/drafts_shareable.go
  internal/cmd/commands/server/server.go
  internal/config/config.go
  pkg/googleworkspace/drive_helpers.go
  pkg/models/document.go
Labels: enhancement, breaking changes

#255 Draft permissions UI
  web/app/components/copy-u-r-l-button.hbs
  web/app/components/copy-u-r-l-button.ts
  web/app/components/document/sidebar.hbs
  web/app/components/document/sidebar.ts
  web/app/components/document/sidebar/header.hbs
  web/app/components/document/sidebar/header.ts
  web/app/components/x/dropdown-list/index.hbs
  web/app/helpers/dasherize.ts
  web/app/modifiers/tooltip.ts
  web/app/styles/components/sidebar.scss
  web/mirage/config.ts
  web/tests/acceptance/authenticated/document-test.ts
  web/tests/integration/components/copy-u-r-l-button-test.ts
  web/tests/integration/helpers/dasherize-test.ts
Labels: enhancement
