Repository hashicorp-forge/hermes, pull requests merged in 2024-04, with the labels that each got.

#664 Add pagination for projects API
  internal/api/v2/projects.go
Labels: enhancement

#666 Enable sending an email to users not found in the Google Workspace directory
  internal/api/v2/me.go
  internal/config/config.go
Labels: enhancement

#660 Support group approvals
  README.md
  configs/config.hcl
  internal/api/v2/approvals.go
  internal/api/v2/documents.go
  internal/api/v2/drafts.go
  internal/api/v2/groups.go
  internal/api/v2/helpers.go
  internal/api/v2/projects_related_resources.go
  internal/api/v2/reviews.go
  internal/cmd/commands/server/server.go
  internal/config/config.go
  internal/indexer/indexer.go
  internal/indexer/refresh_headers.go
  pkg/document/document.go
  pkg/document/replace_header.go
  pkg/googleworkspace/service.go
  pkg/models/document.go
  pkg/models/document_group_review.go
  pkg/models/document_group_review_test.go
  pkg/models/gorm.go
  pkg/models/group.go
  pkg/models/group_test.go
Labels: enhancement, breaking changes

#671 Projects pagination: Reset page count when clicking segmented control
  web/app/components/projects/index.hbs
  web/tests/acceptance/authenticated/projects-test.ts
Labels: bugfix

#661 Add support for Google Groups in the approver field
  web/app/adapters/group.ts
  web/app/components/document/index.hbs
  web/app/components/document/index.ts
  web/app/components/document/sidebar.hbs
  web/app/components/document/sidebar.ts
  web/app/components/editable-field.hbs
  web/app/components/editable-field.ts
  web/app/components/inputs/people-select.hbs
  web/app/components/inputs/people-select.ts
  web/app/components/person/avatar.hbs
  web/app/components/person/avatar.ts
  web/app/components/person/index.hbs
  web/app/components/person/index.ts
  web/app/controllers/authenticated/document.ts
  web/app/helpers/get-model-attr.ts
  web/app/models/group.ts
  web/app/routes/authenticated/document.ts
  web/app/serializers/group.ts
  web/app/serializers/person.ts
  web/app/services/_store.ts
  web/app/styles/app.scss
  web/app/styles/components/multiselect.scss
  web/app/styles/components/person.scss
  web/app/templates/authenticated/document.hbs
  web/app/types/document.d.ts
  web/app/utils/get-model-attr.ts
  web/mirage/config.ts
  web/mirage/factories/group.ts
  web/mirage/models/group.ts
  web/tests/acceptance/authenticated/document-test.ts
  web/tests/integration/components/inputs/people-select-test.ts
  web/tests/integration/components/person/avatar-test.ts
  web/tests/integration/helpers/get-model-attrs-test.ts
Labels: enhancement

#672 Show group approvers in "Request review" modal
  web/app/components/document/sidebar.hbs
  web/tests/acceptance/authenticated/document-test.ts
Labels: bugfix

#674 Make group approvals conditional based on config
  README.md
  configs/config.hcl
  internal/api/v2/groups.go
  internal/config/config.go
  web/app/components/dashboard/new-features-banner.hbs
  web/app/components/dashboard/new-features-banner.ts
  web/app/components/document/sidebar.hbs
  web/app/config/environment.d.ts
  web/app/routes/authenticated/document.ts
  web/app/services/config.ts
  web/app/styles/components/dashboard.scss
  web/mirage/utils.ts
  web/web.go
Labels: breaking changes
